### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by bzg** [ia-flash/app#1]
I suggest using the [Apache 2.0 license](https://fr.wikipedia.org/wiki/Licence_Apache). Let me know if you want me to make a PR.

**Comment by bzg** [comment]
Let me know if I can help with this. Thanks!

**Comment by cristianpb** [comment]
Thanks for the Issue. 
Solved in 71bcbc8b41e6ae6a5664300a0ea18bd46604f037

**Comment by bzg** [comment]
Thanks for fixing it!
